version: '3.9'
name: jobwave

networks:
  broker:
    name: "jobwave-broker-network"
  gateway:
    name: "jobwave-gateway-network"

include:
  # backbone services
  - docker/services/backbone/gateway.yml
  - docker/services/backbone/broker.yml

  # functional services
  - docker/services/auth.yml
