version: '3.9'
name: jobwave

networks:
  broker:
    name: "jobwave-broker-network"
  gateway:
    name: "jobwave-gateway-network"

include:
  # backbone services
  - docker/services/api-gateway.yml
  - docker/services/broker.yml
