
networks:
  broker:
    name: "jobwave-broker-network"

services:
  kafka:
    image: 'bitnami/kafka:3.6.0-debian-11-r0'
    networks:
      - broker
    volumes:
      - ./data/kafka:/bitnami/kafka
    environment:
      # TODO: use Zookeeper for production
      # KRaft config
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
