version: '3.9'

networks:
  # Internal network for the API Gateway
  gateway-internal:
    name: "jobwave-gateway-internal"

secrets:
  gateway_db_password:
    file: ../config/secrets/gateway_db_password

services:
  kong-migrations:
    depends_on:
      - gateway-db
    image: 'kong:3.3.1-alpine'
    container_name: 'jobwave-gateway-migrations'
    networks:
      - gateway-internal
    command: 'kong migrations bootstrap'
    environment:
      KONG_DATABASE: postgres
      KONG_PG_USER: kong
      KONG_PG_HOST: gateway-db
      KONG_PG_PASSWORD_FILE: /run/secrets/gateway_db_password
    secrets:
      - gateway_db_password
    restart: on-failure

  kong-migrations-up:
    image: 'kong:3.3.1-alpine'
    container_name: 'jobwave-gateway-migrations-up'
    networks:
      - gateway-internal
    command: 'kong migrations up && kong migrations finish'
    depends_on:
      - gateway-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_USER: kong
      KONG_PG_HOST: gateway-db
      KONG_PG_PASSWORD_FILE: /run/secrets/gateway_db_password
    secrets:
      - gateway_db_password
    restart: on-failure

  kong:
    image: 'kong:3.3.1-alpine'
    container_name: 'jobwave-gateway'
    user: kong
    depends_on:
      - gateway-db
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
      - ../config/gateway:/opt/kong
    networks:
      - gateway
      - gateway-internal
    environment:
      # Database
      KONG_DATABASE: postgres
      KONG_PG_USER: kong
      KONG_PG_HOST: gateway-db
      KONG_PG_PASSWORD_FILE: /run/secrets/gateway_db_password
      # Admin
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      # FIXME: change values for admin panels to safe values (127.0.0.1)
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_URL: http://localhost:8002
      # Proxy
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      # Configs
      KONG_PREFIX: /var/run/kong
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yml"
    secrets:
      - gateway_db_password
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "0.0.0.0:8443:8443/tcp"
      - "0.0.0.0:8001:8001/tcp"
      - "0.0.0.0:8444:8444/tcp"
      - "0.0.0.0:8002:8002/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    read_only: true
    security_opt:
      - no-new-privileges

  gateway-db:
    image: 'postgres:16-alpine3.18'
    container_name: 'jobwave-gateway-db'
    networks:
      - gateway-internal
    volumes:
      - ../data/gateway:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD_FILE: /run/secrets/gateway_db_password
    secrets:
      - gateway_db_password
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "kong",
          "-U",
          "kong"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true

volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs